# Site settings
title: Resume & Cover Letter Experts
description: The resume writing service for job seekers. Carefully crafted resumes and cover letters that get more interviews. 
baseurl: ""
url: "https://lilypadresumes.com"
email: gethired@lilypadresumes.com
timezone: America/Winnipeg
google_analytics: UA-96566297-1
repository: chrissavoie/lilypadresumes

# Collections
collections:
  posts:
    output: true
    permalink: /:title
  products:
    output: true
    permalink: /:title

# Extras
#gems:
#  - jekyll-contentblocks

# URL Vars
urls:
  twitter:            https://twitter.com/lilypadjobs
  facebook:           https://www.facebook.com/LilyPad-Resumes-1852637254993095/

# Build settings
markdown: kramdown
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  